name: build
on: [push, pull_request]

jobs:
  hw1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hw1/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Test assignment
        run: make

  hw2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Compile dependencies
        run: ./build-dep.sh

      - name: Test assignment
        working-directory: ./hw2
        run: make

  hw3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Compile dependencies
        run: ./build-dep.sh

      - name: Test assignment
        working-directory: ./hw3
        run: make

  midterm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Compile dependencies
        run: ./build-dep.sh

      - name: Test assignment
        working-directory: ./midterm
        run: make

  hw4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Compile dependencies
        run: ./build-dep.sh

      - name: Test assignment
        working-directory: ./hw4
        run: make

  hw5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Compile dependencies
        run: ./build-dep.sh

      - name: Test assignment
        working-directory: ./hw5
        run: make

  hw6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Compile dependencies
        run: ./build-dep.sh

      - name: Test assignment
        working-directory: ./hw6
        run: make

  final:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Compile dependencies
        run: ./build-dep.sh

      - name: Test assignment
        working-directory: ./final/Final
        run: make
