name: build
on: [push, pull_request]

jobs:
  hw1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hw1/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Coq
        run: sudo snap install coq-prover

      - name: Make
        run: make
